Add purge
ib-ai/ib.py pull request #13
Opened 2022-12-28 15:25 UTC by MaxGurbanli

2022-12-29 02:37 UTC, raynichc reviewed
I've only got a few comments, but overall I'm happy with most of the PR. Thanks for your help!

2022-12-29 02:37 UTC, raynichc commented on cogs/moderation.py
> +        Ban a user (including those that are not in the server).
I would personally prefer if this command only worked for those not in the server, as I believe thats how it currently works in IB.ai. When possible, mods should use the built-in discord functionality to ban people, so this command should really only be used when a person has left the server, in my opinion.

2022-12-29 02:37 UTC, raynichc commented on cogs/moderation.py
> +        pass
Shouldn't this print out the sub-commands?

2022-12-29 02:37 UTC, raynichc commented on cogs/moderation.py
> +    async def reaction(self, ctx: commands.Context, number: int):
This is not the correct implementation I believe. The command should take in a specific message (i.e. a channel, then a message in the channel) and then also the reaction to purge from it.

2022-12-29 02:37 UTC, raynichc commented on cogs/public.py
> +        embed.set_author(name=f'{user.name}\'s banner', icon_url=user.display_avatar.url)
I think in this context, its better to use double quotation marks for the string, so that you don't have to escape the single quote.

2022-12-29 02:37 UTC, raynichc commented on cogs/public.py
> +        await ctx.reply(embed=discord.Embed(description=f'I don\'t see how this will help you, but my ping is `{round(self.bot.latency * 1000)}ms`',color=discord.Color.orange()))
I think in this context, its better to use double quotation marks for the string, so that you don't have to escape the single quote.

2022-12-29 11:53 UTC, NathanealV requested changes
A couple more general additions to your PR:
- Seems like there are still some remaining `delete_after`s with your `ctx.reply`. The one present for message purge command should suffice.
- Just to be more consistent with the rest of the codebase, could you change your `ctx.reply`s to `ctx.send`?

Thanks!

2022-12-29 11:53 UTC, NathanealV commented on cogs/moderation.py
> +        if not ctx.invoked_subcommand:
We have a method for exactly this - `available_subcommands` in `utils.commands`

2022-12-29 11:53 UTC, NathanealV commented on cogs/moderation.py
> +    async def reaction(self, ctx: commands.Context, channel: discord.TextChannel, message_id: int, emoji: str):
Shouldn't `emoji` be some type of EmojiConverter? How would it work when a member provides an emote directly?

2022-12-29 11:53 UTC, NathanealV commented on cogs/public.py
> +    async def avatar(self, ctx: commands.Context, user: discord.User = None):
Might be worth adding an option to retrieve (if available) a user's guild-specific avatar

2022-12-29 11:53 UTC, NathanealV commented on cogs/public.py
> +        embed = discord.Embed(description=f"I don't see how this will help you, but my ping is `{round(self.bot.latency * 1000)}ms`", color=discord.Color.orange())
Very small, but there's a missing period at the end of the f-string 😂

2022-12-29 11:53 UTC, NathanealV commented on cogs/public.py
> +    async def userinfo(self, ctx: commands.Context, member: discord.Member = None):
Great start on this feature - but you might want to add a couple more fields. Refer to the relevant code snippet in [the original IB.ai's implementation of this command](https://github.com/ib-ai/IB.ai/blob/729ff5c5201aa30dcc96dd1e0f19a486ef314466/src/main/java/com/ibdiscord/command/registrar/RegistrarUtil.java#L358).

2022-12-29 11:53 UTC, NathanealV commented on cogs/public.py
> +        embed.set_image(url=user.banner.url if user.banner else None)
Instead of sending an empty embed, it might be better to simply send a message saying that the user does not have a banner set.

2022-12-29 11:53 UTC, NathanealV commented on cogs/public.py
> +    async def avatar(self, ctx: commands.Context, user: discord.User = None):
This command has `discord.User` as its argument - does it throw any errors when a user not in the guild is provided?

2022-12-29 12:35 UTC, MaxGurbanli commented
Couldn't fit into commit message but also added more fields to userinfo

2022-12-31 09:17 UTC, NathanealV approved these changes
LGTM!

2022-12-31 09:21 UTC, merged