Feature/tags
ib-ai/ib.py pull request #24
Opened 2023-05-01 11:42 UTC by NathanealV

- [Added tag create, delete, list, and toggle commands](https://github.com/ib-ai/ib.py/commit/821d44af16e6ade536867d0f3e0fce09878f16d7)
- [Added tags to cached.py](https://github.com/ib-ai/ib.py/commit/588fedc749fc58a475518a60d6f8067d9eb6f9e9)
- [Changed RegexConverter to class for better typing](https://github.com/ib-ai/ib.py/commit/7215b79409e8da2399078bb1658a6224bb2ce9da)
- [Added disableReply and GuildReply tables](https://github.com/ib-ai/ib.py/commit/e720efa0ba9f651ca31d2fa6e146bb3755ec4035)

2023-05-30 11:13 UTC, ilikecubesnstuff requested changes
Thank you for implementing the tags feature! My main feedback is about merging the new `GuildReply` model with the existing `GuilData` model. Apart from that, I have a bunch more small comments in various places.

2023-05-30 11:13 UTC, ilikecubesnstuff commented on db/models.py
> +class GuildReply(Model):
Something like `GuildSuppressReply` is a more intuitive name.

2023-05-30 11:13 UTC, ilikecubesnstuff commented on utils/converters.py
It could be worth changing all the converters into classes for consistency's sake.

2023-05-30 11:13 UTC, ilikecubesnstuff commented on db/models.py
> +    channels = ArrayField(element_type="bigint", null = True)
Keyword argument spacing.

2023-05-30 11:13 UTC, ilikecubesnstuff commented on db/cached.py
> +    return await StaffTag.all()
These share a pattern - the code could be condensed with a factory function, e.g.
```py
def model_cache_factory(Model):
    @alru_cache
    async def model_cache() -> list[Model]:
        return await Model.all()
    return model_cache
```

2023-05-30 11:13 UTC, ilikecubesnstuff commented on db/models.py
> +class GuildReply(Model):
Actually, I think this can be combined with the already existing `GuildData` model.

2023-05-30 11:13 UTC, ilikecubesnstuff commented on cogs/tags.py
> +            return
Inconsistency between the if statement and reply?

2023-05-30 11:13 UTC, ilikecubesnstuff commented on cogs/tags.py
> +            await StaffTag.create(trigger=trigger, output=output)
Compress this with `update_or_create`.

2023-05-30 11:13 UTC, ilikecubesnstuff commented on cogs/tags.py
> +            trigger = (await RegexConverter().convert(ctx, trigger)).lower()
Use `RegexConverter` in the function signature as a type annotation.

2023-05-30 11:13 UTC, ilikecubesnstuff commented on cogs/tags.py
> +            tags = [tag for tag in tags if trigger and trigger in tag.trigger.lower()]
The truthiness of `trigger` is already checked, `trigger in tag.trigger.lower()` should be sufficient.

2023-05-30 11:13 UTC, ilikecubesnstuff commented on cogs/tags.py
> +            return
If you merge `GuildReply` into `GuildData`, this part could be cleaner:
```py
guild_data = await get_guild_data(guild_id = message.guild.id)
if message.channel.id in guild_data.suppressed_replies:
    return
```

2023-05-30 11:13 UTC, ilikecubesnstuff commented on cogs/tags.py
> +            if re.fullmatch(tag.trigger.lower(), message.content.lower(), re.IGNORECASE):
I suggest keeping the tag's trigger in its original case. Wait for another opinion, but I remember the lowercasing of triggers causing unexpected behaviors for some regular expressions with special characters (like `\W`, for example).

2023-05-30 11:13 UTC, ilikecubesnstuff commented on cogs/tags.py
> +        await ctx.send(f"Deleted tag `{trigger}`.")
Adding the tag's output in the log and reply would be handy.

2023-05-30 11:13 UTC, ilikecubesnstuff commented on cogs/tags.py
> +            f"{'[Disabled]' if tag.disabled else ''} `{tag.trigger}`" for tag in tags]
This appears to leave a space at the start of non-disabled tags. Is an f-string like ```f"{'[Disabled] ' if tag.disabled else ''}`{tag.trigger}`"``` what is intended?

2023-05-30 11:13 UTC, ilikecubesnstuff commented on cogs/tags.py
> +        await ctx.send(f"Replies for <#{channel.id}> are now {'disabled' if not disabled else 'enabled'}.")
Perhaps move these into `guilddata.py` if you merge `GuildReply` with `GuildData`.

2023-05-30 11:13 UTC, ilikecubesnstuff commented on cogs/tags.py
> +            guild_reply.channels = []
Redundant?

2023-07-03 03:55 UTC, NathanealV commented on cogs/tags.py
> +        await ctx.send(f"Replies for <#{channel.id}> are now {'disabled' if not disabled else 'enabled'}.")
Can be moved when the moderation PR have been merged - ignoring for now.

2023-07-03 04:18 UTC, NathanealV commented
- Removed `.lower()` when checking for tag triggers
- Consistency with checking for tag trigger length
- Replaced redundant code with `update_or_create`
- Adjusted logging and success message for tag delete
- Adjusted `reply` commands for changes to DB schema
- Formatting

2023-07-05 17:12 UTC, ilikecubesnstuff commented on cogs/tags.py
> +        ) > NAME_SIZE_LIMIT - 11:  # 2 for backticks and 9 for [Disabled] with trailing whitespace
Doesn't `[Disabled] ` take up 11 characters? So including the 2 backticks, this should total 13?

2023-07-08 02:12 UTC, ilikecubesnstuff approved these changes

2024-01-10 03:04 UTC, merged