Add Ruff check GitHub Actions push and pull request merge block
ib-ai/ib.py pull request #37
Opened 2024-06-01 10:12 UTC by EdwardTheLegend

Added the `ruff.yml` for the GitHub Actions workflow and also had to force fixes to solve linter violations such as removing unused imports.

Closes #35

2024-06-20 10:58 UTC, NathanealV reviewed
Thank you for the PR! Changes look good - might need to go over some files again with f-strings as they might be over the line length (mostly with `cogs/monitor.py`.

2024-06-20 10:58 UTC, NathanealV commented on cogs/monitor.py
> +            f"The pattern (`{monitored_message.message}`) [ID: {monitored_message.monitor_message_id}] has been successfully {'disabled' if monitored_message.disabled else 'enabled'}."
Line 241 + line 305 are over the 95 character line length (may involve other lines as well). Should probably manually adjust these.

2024-06-23 15:09 UTC, EdwardTheLegend commented
I ran the formatting with the new line length on the whole repo. I think the exceptions you mentioned might be where the ruff rules based on pep standards don't recommend folding on. Some things like long strings aren't usually broken over multiple lines even if they go a bit over the limit.

2024-06-25 20:57 UTC, ilikecubesnstuff requested changes
Apart from my comment and Nath's, this looks fine now. I'll approve after the changes are pushed. Thanks!

2024-06-25 20:57 UTC, ilikecubesnstuff commented on bot.py
>      # 'help',
I assume Ruff missed this because it's commented out, but change these quotation marks as well.

2024-06-30 20:08 UTC, ilikecubesnstuff approved these changes

2024-07-01 08:20 UTC, NathanealV approved these changes
LGTM!

2024-07-01 08:21 UTC, merged